context("General functions")

test_that("polygon and raster overlap", {
  # polygon inside raster
  pol <- as(extent(c(-60,60,-60,60)), "SpatialPolygons")
  proj4string(pol) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

  rst1 <- terra::rast(nrows=4, ncols=4, nlyrs=1, xmin=-70, xmax=70,ymin=-70, ymax=70, crs = "+proj=longlat +datum=WGS84")
  values(rst1) <- rep(0,16)
  # raster inside polygon
  rst2 <- terra::rast(nrows=4, ncols=4, nlyrs=1, xmin=-50, xmax=50,ymin=-50, ymax=50, crs = "+proj=longlat +datum=WGS84")
  values(rst2) <- rep(0,16)
  # intersect
  rst3 <- terra::rast(nrows=4, ncols=4, nlyrs=1, xmin=-50, xmax=50,ymin=-50, ymax=70, crs = "+proj=longlat +datum=WGS84")
  values(rst3) <- rep(0,16)
  # outside
  rst4 <- terra::rast(nrows=4, ncols=4, nlyrs=1, xmin=80, xmax=90,ymin=80, ymax=90, crs = "+proj=longlat +datum=WGS84")
  values(rst4) <- rep(0,16)
  # check if function gives expected output
  expect_equal(ext_overlap(pol,rst1),1)
  expect_equal(ext_overlap(pol,rst2),2)
  expect_equal(ext_overlap(pol,rst3),3)
  expect_equal(ext_overlap(pol,rst4),4)
})

test_that("Generate FORCE folder structure", {
  forcefolder <- tempdir()
  fldrs <- setFolders(forcefolder)
  expect_equal(fldrs[['tmpfolder']], normalizePath('./data/temp'))
  expect_equal(file.exists(fldrs[['tmpfolder']]),TRUE)
  expect_equal(fldrs[['l1folder']], normalizePath('./data/level1'))
  expect_equal(file.exists(fldrs[['l1folder']]),TRUE)
  expect_equal(fldrs[['l2folder']], normalizePath('./data/level2'))
  expect_equal(file.exists(fldrs[['l2folder']]),TRUE)
  expect_equal(fldrs[['queuefolder']], normalizePath('./data/level1'))
  expect_equal(file.exists(fldrs[['queuefolder']]),TRUE)
  expect_equal(fldrs[['queuefile']], 'queue.txt')
  expect_equal(file.exists(normalizePath('./data/level1/queue.txt')),TRUE)
  expect_equal(fldrs[['demfolder']], normalizePath('./data/misc/dem'))
  expect_equal(file.exists(fldrs[['demfolder']]),TRUE)
  expect_equal(fldrs[['wvpfolder']], normalizePath('./data/misc/wvp'))
  expect_equal(file.exists(fldrs[['wvpfolder']]),TRUE)
  expect_equal(fldrs[['logfolder']], normalizePath('./data/log'))
  expect_equal(file.exists(fldrs[['logfolder']]),TRUE)
  expect_equal(fldrs[['paramfolder']], normalizePath('./data/param'))
  expect_equal(file.exists(fldrs[['paramfolder']]),TRUE)
  expect_equal(fldrs[['paramfile']], 'l2param.prm')
  expect_equal(fldrs[['lcfolder']], normalizePath('./data//misc/lc'))
  expect_equal(file.exists(fldrs[['lcfolder']]),TRUE)
  expect_equal(fldrs[['tcfolder']], normalizePath('./data/misc/tc'))
  expect_equal(file.exists(fldrs[['tcfolder']]),TRUE)
  expect_equal(fldrs[['firefolder']], normalizePath('./data/misc/fire'))
  expect_equal(file.exists(fldrs[['firefolder']]),TRUE)
  expect_equal(fldrs[['S2auxfolder']], normalizePath('./data/misc/S2'))
  expect_equal(file.exists(fldrs[['S2auxfolder']]),TRUE)
  expect_equal(fldrs[['demlogfile']], normalizePath('./data/log/DEM.txt'))
  expect_equal(file.exists(fldrs[['demlogfile']]),TRUE)
  expect_equal(fldrs[['wvplogfile']], normalizePath('./data/log/WVP.txt'))
  expect_equal(file.exists(fldrs[['wvplogfile']]),TRUE)
  expect_equal(fldrs[['landsatlogfile']], normalizePath('./data/log/Landsat.txt'))
  expect_equal(file.exists(fldrs[['landsatlogfile']]),TRUE)
  expect_equal(fldrs[['lclogfile']], normalizePath('./data/log/LC.txt'))
  expect_equal(file.exists(fldrs[['lclogfile']]),TRUE)
  expect_equal(fldrs[['firelogfile']], normalizePath('./data/log/fire.txt'))
  expect_equal(file.exists(fldrs[['firelogfile']]),TRUE)
  expect_equal(fldrs[['tclogfile']], normalizePath('./data/log/tc.txt'))
  expect_equal(file.exists(fldrs[['tclogfile']]),TRUE)
  expect_equal(fldrs[['Sskiplogfile']], normalizePath('./data/log/Sskip.txt'))
  expect_equal(file.exists(fldrs[['Ssuccesslogfile']]),TRUE)
  expect_equal(fldrs[['Ssuccesslogfile']], normalizePath('./data/log/Ssuccess.txt'))
  expect_equal(file.exists(fldrs[['Sskiplogfile']]),TRUE)
  expect_equal(fldrs[['Smissionlogfile']], normalizePath('./data/log/Smission.txt'))
  expect_equal(file.exists(fldrs[['Smissionlogfile']]),TRUE)
  expect_equal(fldrs[['Sotherlogfile']], normalizePath('./data/log/Sother.txt'))
  expect_equal(file.exists(fldrs[['Sotherlogfile']]),TRUE)

  unlink(forcefolder, recursive = T)
})

test_that("Maximum value with NA",{
  expect_equal(max_narm(c(1,5,NA, NaN)), 5)
})
